repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.7.0
  hooks:
    - id: ruff
      args: [ --fix ]
    - id: ruff-format

- repo: local
  hooks:
    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: python
      types_or: [python, pyi]
      require_serial: true
